name: CI
on: [push, pull_request]
jobs:
   arch:
      runs-on: ubuntu-latest
      container:
         image: archlinux:latest
         volumes:
            - /dev/kvm:/dev/kvm
      steps:
         - name: Enable KVM group perms
           run: |
               echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | tee /etc/udev/rules.d/99-kvm4all.rules
               udevadm control --reload-rules
               udevadm trigger --name-match=kvm
         - run: pacman --noconfirm --noprogressbar -Syu
         - run: pacman --noconfirm --noprogressbar -S make go asciidoc gcc git edk2-ovmf qemu-system-x86
         - uses: actions/checkout@v1
         - run: git config --global --add safe.directory $(pwd)
         - run: make
         - run: make test
         - run: make integration
         - run: GOBIN=/usr/bin make lint
   void:
      runs-on: ubuntu-latest
      container: ghcr.io/void-linux/void-musl
      steps:
         # update xbps, if necessary
         - run: xbps-install -Syu || ( xbps-install -yu xbps && xbps-install -Syu)
         - run: xbps-install -y make go asciidoc gcc git
         - uses: actions/checkout@v1
         - run: git config --global --add safe.directory $(pwd)
         - run: make
         - run: make test
         - run: GOBIN=/usr/bin make lint
